<?php 

/*PRODUCTO_O_SERVICIO_9*/


$ROW = $proveedoresC->variable_infoimportante();

$NOMBRE_INFORMACION = isset($ROWempresa["NOMBRE_INFORMACION"])?$ROWempresa["NOMBRE_INFORMACION"]:"";
$INFOIMPO_OBSERVACIONES = isset($ROWempresa["INFOIMPO_OBSERVACIONES"])?$ROWempresa["INFOIMPO_OBSERVACIONES"]:"";
$INFORMACION_IMPORTANTE_FECHA = isset($ROWempresa["INFORMACION_IMPORTANTE_FECHA"])?$ROWempresa["INFORMACION_IMPORTANTE_FECHA"]:"";
$hPINFO_IMPORTANTE = isset($ROWempresa["hPINFO_IMPORTANTE"])?$ROWempresa["hPINFO_IMPORTANTE"]:""; 